# Generated by Django 4.2 on 2023-04-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
