# Generated by Django 4.2 on 2023-04-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_table_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card_brand',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_last4',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payer_email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payer_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payer_phone',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
    ]
