# Generated by Django 4.2 on 2023-04-11 20:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_table_number'),
        ('employees', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouporder',
            name='table',
        ),
        migrations.RemoveField(
            model_name='grouporder',
            name='waiter',
        ),
        migrations.RemoveField(
            model_name='personalorder',
            name='parent_order',
        ),
        migrations.RemoveField(
            model_name='personalorder',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='personalorder',
            name='tip',
        ),
        migrations.AddField(
            model_name='grouporder',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_order', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='grouporder',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='personalorder',
            name='parent_group_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_orders', to='orders.grouporder'),
        ),
        migrations.AlterField(
            model_name='grouporder',
            name='group_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='TableOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.table')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.table')),
                ('target_waiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.AddField(
            model_name='grouporder',
            name='table_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_orders', to='orders.tableorder'),
        ),
        migrations.AddField(
            model_name='personalorder',
            name='table_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_orders', to='orders.tableorder'),
        ),
    ]
