# Generated by Django 4.2 on 2023-04-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_notification_options_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('closed', 'Closed')], default='pending', max_length=10),
        ),
    ]
