# Generated by Django 4.2 on 2023-04-30 13:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_table_number'),
        ('orders', '0007_alter_tableorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorder',
            name='accepted_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 30, 13, 10, 29, 948393, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='tableorder',
            name='closed_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 30, 13, 10, 29, 948393, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='tableorder',
            name='pending_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 30, 13, 10, 29, 948393, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tableorder',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_orders', to='billing.table'),
        ),
    ]
