# Generated by Django 4.2 on 2023-04-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_tableorder_accepted_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableorder',
            name='accepted_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tableorder',
            name='closed_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tableorder',
            name='pending_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
